services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    user: "user:user"
    volumes:
      - .:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/user/opencv/build:/opencv:ro
      - /home/user/Videos:/videos:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    hostname: dev
    extra_hosts:
      - "dev:127.0.0.1"
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      - /dev/dri:/dev/dri
    privileged: true