services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.cuda.jetson
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
